services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s      
      timeout: 5s       
      retries: 10      
      start_period: 5s 
    networks:
      - dev

  nextjs:
    container_name: frontend
    image: nextjs-app:latest
    # Убираем проброс портов, так как Nginx будет проксировать запросы
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - dev

  bookapp:
    container_name: backend
    image: alljay2/bookstoreapi
    environment:
      - ASPNETCORE_HTTP_PORTS=5008
    ports:
      - "5008:5008"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # для HTTPS, если потребуется
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # для SSL сертификатов
    depends_on:
      - nextjs
    restart: unless-stopped
    networks:
      - dev

volumes:
  postgres-data:

networks:
    dev: